### ISSUE TITLE
Cannot load plugin `org_reader`

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican-plugins#1045]
```
pelican /var/www/html/tests/libremanuals/content -o /var/www/html/tests/libremanuals/pages -s /var/www/html/tests/libremanuals/pelicanconf.py 
ERROR: Cannot load plugin `org_reader`
  | ImportError: No module named 'orgco'
```

I had to rename the plugin folder to `org_reader` and change its `__init__.py` file to make it work. The documentation should be changed or you should make it so that it works following the documentation. There was a big change lately in #1039. @jappeace, I don't know if that's the cause; if so, can you make it work please.

**Comment by jappeace** [comment]
I undid an api change, this should use the same code as before.

Anyway, don't rename your plugin folder. You seem to be using the new org_reader now which should be opt in. try using org_reader instead of org_python_reader. If you want to use org_python_reader you should install orgco which does the parsing of org in python

**Comment by jorgesumle** [comment]
The README from Org Reader plugin reads:

> PLUGINS = ['org_reader']

That doesn't work and should be fixed.

**Comment by jappeace** [comment]
The big change was to prevent these issues. I'm not sure why you're having them.  the python based reader should be opt in as it may not support org as expected.

I'm not sure why it's going wrong on your machine. I'd suggest checking if you're on the right commit in pelican plugins. This commit works for me `ead70548ce2c78ed999273e265e3ebe13b747d83` (which is the latest I believe).

Good luck.
