### ISSUE TITLE
Archlinux: unable to load tcltk on installation

### ISSUE THREAD

**Issue by iacchus** [getpelican/pelican-plugins#1216]
When I issued `R> install.packages('knitr')`

Solution here: https://github.com/rstudio/shiny/issues/52

**Comment by Lucas-C** [comment]
Could you explain a little bit more your issue here ?
With what plugin do you encounter this issue ? In what context do you issue this `R` command, and what is the link with this repo ?

**Comment by iacchus** [comment]
I use Archlinux. When installing your plugin following your instructions I've got the error in R console:

`unable to load tcltk on installation`

Archlinux users need to install the `tk` with the command

`sudo pacman -S tk`

Before doing 

`R> install.packages('knitr')`

**Comment by Lucas-C** [comment]
Thanks for the in-depth explanation.

Maybe you could submit a PR to add to `rmd_reader/README.md` a mention about the issue you faced and the workaround you found ?

About having a repo for each plugin, this is always a possibility. This repo, `pelican-plugins`, gather efforts to maintain a collection of "community suported" plugins. @wilsonfreitas initiated the `rmd_reader` plugin in 2014, any other people contributed to it since. It is still possible to extract it in a dedicated repo, and publish it on Pypi, but that would also have its downsides. @wilsonfreitas maybe you have an opinion about it ?

**Comment by wilsonfreitas** [comment]
The problem relies on knitr, it has many dependencies not directly related to R and it is handled differently among OSs. I developed this plugin using MacOS and I know from others that it runs on Windows and Ubuntu.
I'm not sure that having a separate repo will solve this problem, but I see your point. We might have an opportunity here.
For now, agree with @Lucas-C, an update to README.md would help on this subject.

**Comment by justinmayer** [comment]
> wouldn't be better if we had a repo for each plugin or theme? because we have to download each plugin manually and the repositories (plugins and themes) are getting big.

That is [already planned](https://github.com/getpelican/pelican/issues/1488). It's just a question of finding the time to move that effort forward.

> It is still possible to extract it in a dedicated repo, and publish it on PyPI, but that would also have its downsides.

If there are concerns with the above-mentioned plan, please feel free to express them in the relevant issue linked above.

**Comment by Lucas-C** [comment]
@iacchus Do the comments above answer your initial questions / request ?
Do you plan to help on this subject, or maybe else can this issue be close ?
