### ISSUE TITLE
Sitemap plugin doesn't work with custom PAGE_SAVE_AS setting

### ISSUE THREAD

**Issue by rdegges** [getpelican/pelican-plugins#1275]
Hi there.

I'm using the wonderful `sitemap` plugin included with this repo to dynamically generate a sitemap.xml for my website. My website contains a collection of top-level pages, for example:

-` /` (index page)
- `/quickstart` (quickstart page)
- `/about` (about page)
- etc.

By default, with Pelican, when I created my pages, they were all generated as `/pages/{slug}.html`, which is the default value of the `PAGE_SAVE_AS` setting. In order for me to generate pretty URLs for my pages as described above, I had to modify that setting, which now looks like the following:

```python
PAGE_SAVE_AS = '{slug}/index.html'
```

Unfortunately, it appears that the sitemap plugin does not respect this setting, so even though I have a `/quickstart` page, for example, my sitemap.xml file incorrectly refers to that page as `/pages/quickstart.html`.

For reference, here is my plugin configuration:

```python
PLUGINS = ['sitemap']
PLUGIN_PATHS = ['plugins']

SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 0.5,
        'indexes': 0.5,
        'pages': 0.5,
    },
    'changefreqs': {
        'articles': 'monthly',
        'indexes': 'daily',
        'pages': 'monthly',
    },
    'exclude': ['archives', 'authors', 'categories', 'tags']
}
```

**Comment by justinmayer** [comment]
Hey Randall. Long time no see. 👋 

Since we have been slowly migrating plugins from this monolithic repository to their own individual repositories under the new [Pelican Plugins organization](https://github.com/pelican-plugins), it is probably wise to check whether you can replicate the problem with the code from the new [Sitemap plugin repository](https://github.com/pelican-plugins/sitemap). I don't think it has diverged much from the code here, but would you double-check and let us know?

For what it's worth, I use the new repo's version with settings that are nearly identical to yours, and the page links in the sitemap file are generated as one would expect: https://justinmayer.com/sitemap.xml

If that does resolve the problem, please accept my apologies for the confusion. Putting a deprecation notice into the README of migrated plugins is one of the outstanding items on my to-do list. 😅

**Comment by avaris** [comment]
You need to define a matching `PAGE_URL` too. Or did you leave it as default?

**Comment by rdegges** [comment]
Hey @justinmayer, indeed! Has been a while =)

I'll take a look at the new repo. I haven't used Pelican in a while, but am just getting back into it for some projects, so excited to relearn the ecosystem =)

**Comment by justinmayer** [comment]
Hey Randall! If you can replicate this on the aforementioned new repo for the Sitemap plugin, by all means please re-submit this issue there. Hoping to publish the next (namespace-plugin-ready) Pelican release tomorrow! ✨
