### ISSUE TITLE
Tipue.com is now a site about london sex vampires.

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican-plugins#1283]
We should probably link to https://github.com/michael-milette/Tipue-Search instead.

**Comment by markusgoller** [comment]
Yes, that is true :-)!

**Comment by markusgoller** [comment]
@GiovanH thank you for the real link.

**Comment by kdeldycke** [comment]
https://github.com/michael-milette/Tipue-Search seems to be outdated: it only got version 6.0 while it seems Tipue 7.1 was the last revision.

I managed to track it down in thw Wayback Machine at: https://web.archive.org/web/20200703134724/https://tipue.com/search/

Direct link to archive seems to be: https://web.archive.org/web/20200703134724/https://www.tipue.com/search/tipuesearch.zip

**Comment by jorgesumle** [comment]
I got version 7.1 before it was taken down. Check it out here: https://notabug.org/jorgesumle/Tipue-Search

**Comment by kdeldycke** [comment]
Since I'm about to finish the [migration of the plugin to its own independent Python package](https://github.com/pelican-plugins/tipue-search/pull/1), I added a note in the README to address that issue: https://github.com/pelican-plugins/tipue-search/pull/1/commits/7b12cd9d6eeba703ac6782807240ce31ac1834c8 .

We can now close this issue.
