### ISSUE TITLE
[Migration] pelican-linkclass, libravatar, pelican_md_graphviz, and pelican_md_include

### ISSUE THREAD

**Issue by rlaboiss** [getpelican/pelican-plugins#1311]
Dear Pelican developers,

I currently maintain four Pelican plugins, which are in different situations:

- [x] **[Migrated!](https://github.com/pelican-plugins/linkclass)** ~~[pelican-linkclass](https://github.com/rlaboiss/pelican-linkclass/), which is maintained in a personal GitHub repository. This plugin [has been published](https://pypi.org/project/pelican-linkclass/) on PyPI.~~
- [x] **[Migrated!](https://github.com/pelican-plugins/avatar)** ~~[libravatar](https://github.com/getpelican/pelican-plugins/tree/master/libravatar), which is currently part of the pelican-plugins monolithic repo.~~
- [x] **[Migrated!](https://github.com/pelican-plugins/graphviz)** ~~[pelican_md_graphviz](https://github.com/rlaboiss/pelican_md_graphviz), which is maintained in a personal GitHub repository.~~
- [x] **[Migrated!](https://github.com/pelican-plugins/markdown-include)** ~~[pelican_md_include](https://github.com/rlaboiss/pelican_md_include), which is maintained in a personal GitHub repository.~~

All these plugins are functional with Pelican 4 and Python 3. I would love to migrate them into the new Pelican Plugins organization and also to publish the last three on PyPI. Guidance from a Pelican developer will be highly appreciated.

Best,

Rafael Laboissière

**Comment by rlaboiss** [comment]
According to the [new procedure](https://github.com/getpelican/pelican-plugins#pelican-plugins), a Pelican maintainer should guide me through the process. Will that ever happen or should I just be patient?

**Comment by justinmayer** [comment]
Sincere apologies, Rafael. I'll reach out tomorrow so we can begin the process together. Thanks for your patience! 😅

**Comment by rlaboiss** [comment]
No worries, Justin. We are all overbooked. Thanks for your work supporting Pelican.

**Comment by justinmayer** [comment]
Thanks for the kind words! 😊 I sent you a message via email re: next steps.

By the way, do you think it would make sense to combine the Libravatar and Gravatar plugins into a single plugin? I haven't looked at the respective source, mind you. Generally speaking I find it preferable to avoid unnecessary plugin fragmentation, but I would welcome comments regarding feasibility in this specific case.

**Comment by rlaboiss** [comment]
Thanks, I followed the instructions in the email message.

As regards merging the Libravatar and Gravatar, I thing it may be a good idea. However, keeping backward compatibility may be tricky, since the Libravatar plugin introduces some specific configuration variables.

**Comment by justinmayer** [comment]
[Link Class plugin has been migrated.](https://github.com/pelican-plugins/linkclass). 🎉 Many thanks to Rafael for his assistance and patience with that process! 😅 

@rlaboiss: Question about [pelican_md_graphviz](https://github.com/rlaboiss/pelican_md_graphviz)… Does it do something beyond that which the corresponding [Liquid-style Graphviz tag](https://github.com/pelican-plugins/liquid-tags/blob/main/pelican/plugins/liquid_tags/graphviz.py) accomplishes? I know that tag did not exist when you created the separate Graphviz plugin, but now that such a tag does exist, is there a compelling reason for there to be a separate plugin?

**Comment by rlaboiss** [comment]
> @rlaboiss: Question about [pelican_md_graphviz](https://github.com/rlaboiss/pelican_md_graphviz)… Does it do something beyond that which the corresponding [Liquid-style Graphviz tag](https://github.com/pelican-plugins/liquid-tags/blob/main/pelican/plugins/liquid_tags/graphviz.py) accomplishes? I know that tag did not exist when you created the separate Graphviz plugin, but now that such a tag does exist, is there a compelling reason for there to be a separate plugin?

I do not remember if I was aware of the existence of liquid_tags/graphviz when I created my pelican_md_graphviz plugin. If I was aware of it, then I should have had a compelling reason for creating my plugin. Besides the implementation being totally different (my plugin works via a MarkDown extensions), I do not see big differences in functionality between the two plugins. I will check this more carefully and will come back to you later.

**Comment by rlaboiss** [comment]
At any rate, there is at least one user of the md_graphviz plugin who filed an issue on the corresponding repository: https://github.com/rlaboiss/pelican_md_graphviz/issues/2

**Comment by rlaboiss** [comment]
> I do not remember if I was aware of the existence of liquid_tags/graphviz when I created my pelican_md_graphviz plugin. If I was aware of it, then I should have had a compelling reason for creating my plugin.

I found [the reason](https://github.com/rlaboiss/pelican_md_graphviz#alternatives) why I wrote the pelican_md_graphviz.

**Comment by rlaboiss** [comment]
> Besides the implementation being totally different (my plugin works via a MarkDown extensions), I do not see big differences in functionality between the two plugins. I will check this more carefully and will come back to you later.

I checked the differences between the two plugins:

- **Implementation**: _liquid_tags.graphviz_ use the liquid_tag syntax `{% graphviz { <program> […] } %}`, while _pelican_md_graphviz_ uses the Markdown extension syntax `..graphviz <program> […]`
- **Output**:
  - Both plugins output an element with `class="graphviz"`. However, only _pelican_md_graphviz_ allow to change the class name through a configuration variable (`MD_GRAPHVIZ_IMAGE_CLASS`).
  - _liquid_tags.graphviz_ encodes the image as `src="data:image/png;base64,[…]"`, while _pelican_md_graphviz_ encodes it as `src="data:image/svg+xml;base64,[…]"`. This has two impacts:
    - The size of the produced HTML code is much smaller for _pelican_md_graphviz_. For instance, the a base64 string for the Graphviz code `digraph graphname {a -> b -> c; b -> d;}` is four times smaller with _pelican_md_graphviz_.
    - The output of _liquid_tags.graphviz_ is pixelated, while the output of _pelican_md_graphviz_ is vectorial and the resulting web page can be zoomed without loss of quality.
  - _liquid_tags.graphviz_ outputs the Graphviz image inside a `<span>`, while _pelican_md_graphviz_ does it inside a `<div>`. There are merits in both of this options, but the ideal situation would have the choice of the container element to be set in the configuration file. I might consider adding an option for choosing the container element in _pelican_md_graphviz_.

**Comment by justinmayer** [comment]
@rlaboiss: Many thanks for the detailed explanation. It seems there is indeed value in retaining and migrating your Graphviz-related plugin. I asked these questions (and I will eventually add this to the migration guide) because they relate to some thoughts I have regarding Pelican plugin migration goals:

1. **Consolidation can help avoid too many plugins** — When there are multiple plugins with overlapping functionality, combining their collective feature set into a single plugin (or if applicable, choosing one over the others) significantly reduces maintenance overhead. Avoiding plugin fragmentation also eliminates end-user confusion about: “How are these plugins different? Which one should I install?”

2. **General is better than specific** — For example, one plugin that implements a feature for both Markdown and reStructuredText is better than two separate plugins, one for each markup format.

3. **Simple names are better than complex** — Related to both (1) and (2) above. Choosing simple, generalized, and comprehensive names helps ensure that the plugin will not “out-grow” its name as new features and capabilities are added.

(I’m sure I’ll think of other objectives, but at least that’s a start.)

With that in mind, I think it would be better for your Graphviz plugin to be simply named _Graphviz_, with the package to be named `pelican-graphviz`. I realize that the “md” in the original name was probably intended to convey that the plugin only supports Markdown, but I think that can adequately be expressed at the beginning of the README. That way, if someone later decides to add reStructuredText support, that can be done without creating an entirely new repository, renaming the plugin and package names, et cetera. (Renaming PyPI packages is particularly problematic.) Does that make sense?

Assuming that seems sensible to you, I propose that we start by creating a new repository at https://github.com/pelican-plugins/graphviz. For Link Class, we transferred the repository instead because there were enough issues and PRs that it made sense to retain that history, but in the case of `pelican-md-graphviz` there doesn’t seem much to preserve, and creating a new repository makes certain things easier from a migration perspective (e.g., no need to rename the primary branch, etc.).

Would you please let me know your thoughts on the above? If it all sounds okay, I’ll create the new repo, add the initial commit, and then pass the baton so you can create a `migrate` branch and carry out the rest of the steps in the migration guide. :dizzy:

**Comment by rlaboiss** [comment]
Your plan sounds sensible tp me. Go ahead and I will catch up.

**Comment by rlaboiss** [comment]
@justinmayer: When are you planning to create the new repository? I am asking this because I could make the changes for getting rid of the `md_` prefix in the code before the repository migrates into the Pelican Plugins organization. I am also considering the addition of a configuration variable for choosing between the `<span>` and `<div>` containers for the output. I will also change the `master` branch into `main`. Finally, I would prefer to import the whole Git history into the new repository, instead of importing the sources and making an initial commit.

**Comment by rlaboiss** [comment]
@justinmayer: Ok, I did everything I mentioned above without waiting for your reply:
- https://github.com/rlaboiss/pelican_md_graphviz/commit/babb135df3792cb8cc171eaf6607ffc23346e04e: Introduce GRAPHVIZ_HTML_ELEMENT configuration variable
- https://github.com/rlaboiss/pelican_md_graphviz/commit/c1ed906e036176e7bdbe39a579e305921221fbd7: Get rid of the "MD_" prefix and the "_md_" part in the name of the test file
- renamed branch `master` ⇒ `main`

**Comment by justinmayer** [comment]
> When are you planning to create the new repository?

Done! Link: https://github.com/pelican-plugins/graphviz

> I did everything I mentioned above without waiting for your reply

Great. I pulled in the entire history, including today's commits, into the new repository above.

As far as next steps, my suggestion would be to follow the [Plugin Migration Guide](https://blog.getpelican.com/namespace-plugin-migration.html), beginning with the _Updating the Plugin_ section. (In this case, we have already put the existing commits into `main` instead of a `migrate` branch, but otherwise we should be able to follow the guide from that point.)

So would you be willing to create a new `migrate` branch on your local workstation, make the changes indicated in the guide (and commit at the specified points), push your `migrate` branch to the new repository, and submit a pull request from that branch? Excited to see another plugin transform into a new shiny namespace plugin! 😊

**Comment by justinmayer** [comment]
I created an issue for the Graphviz plugin migration, so perhaps we should move the discussion for this particular plugin's migration to that issue: https://github.com/pelican-plugins/graphviz/issues/1

**Comment by rlaboiss** [comment]
> I created an issue for the Graphviz plugin migration, so perhaps we should move the discussion for this particular plugin's migration to that issue: [pelican-plugins/graphviz#1](https://github.com/pelican-plugins/graphviz/issues/1)

Ok, thanks

**Comment by rlaboiss** [comment]
> By the way, do you think it would make sense to combine the Libravatar and Gravatar plugins into a single plugin? I haven't looked at the respective source, mind you. Generally speaking I find it preferable to avoid unnecessary plugin fragmentation, but I would welcome comments regarding feasibility in this specific case.

Looking again at the six-years old code, I just remembered that my libravatar plugin works transparently for Gravatar accounts. The default behavior of Libravatar is to proxy (anonymously) the requests to Gravatar, if no local avatar was found.

Would it be sensible to rename my plugin to, say, "avatar" and advertize it as a generic Libravatar/Gravatar plugin? This would address your concern, I think.

**Comment by rlaboiss** [comment]
> Would it be sensible to rename my plugin to, say, "avatar" and advertize it as a generic Libravatar/Gravatar plugin? This would address your concern, I think.

Ok, I gave it a try. I created a new plugin, based in my previous libravatar one, and put it in a [separated repo](https://github.com/rlaboiss/pelican-avatar). I followed the [migration guide](https://blog.getpelican.com/namespace-plugin-migration.html), so the code should be ready to go into Pelican Plugins (well, there is a linter issue that I could not succeed to fix).

**Comment by rlaboiss** [comment]
> Ok, I gave it a try. I created a new plugin, based on my previous libravatar one, and put it in a [separated repo](https://github.com/rlaboiss/pelican-avatar). I followed the [migration guide](https://blog.getpelican.com/namespace-plugin-migration.html), so the code should be ready to go into Pelican Plugins (well, there is a linter issue that I could not fix).

I just [added](https://github.com/rlaboiss/pelican-avatar/commit/f475708651c99306b626e150f5ba5072807bf3fe) an option called AVATAR_USE_GRAVATAR that allows the use of Gravatar directly instead of Libravatar. With this change, the avatar plugin fully complies with @justinmayer's [request](https://github.com/getpelican/pelican-plugins/issues/1311#issuecomment-765500685).

**Comment by rlaboiss** [comment]
I have also migrated my [md-include](https://github.com/rlaboiss/pelican_md_include) plugin to the new Pelican plugins conventions.

**Comment by rlaboiss** [comment]
Regarding my avatar plugin, I have just merge [PR #1](https://github.com/rlaboiss/pelican-avatar/pull/1) from @troycurtisjr, which contains an important improvement in the plugin code.

**Comment by justinmayer** [comment]
The [Graphviz plugin](https://github.com/pelican-plugins/graphviz) has been migrated and published to PyPI, and the [Avatar plugin](https://github.com/pelican-plugins/avatar) is awaiting final review. 🎉

**Comment by rlaboiss** [comment]
> I have also migrated my [md-include](https://github.com/rlaboiss/pelican_md_include) plugin to the new Pelican plugins conventions.

Hello Justin, I hope you are doing well. Is there any chance to get the md_include plugin also migrated to the Pelican Plugins organization?

**Comment by justinmayer** [comment]
Hey Rafael. I’m very sorry for the long delay. I am traveling at the moment but should be able to get to this next week. Thank you for your patience!

**Comment by rlaboiss** [comment]
No problem, Justin, take you time.

**Comment by rlaboiss** [comment]
Getting back to this old issue: I recently updated my repository [rlaboiss/pelican_md_include](https://github.com/rlaboiss/pelican_md_include). Any chance this can be migrated?

**Comment by rlaboiss** [comment]
This is just a periodic ping to be sure that this issue does not fall into oblivion 😉

**Comment by justinmayer** [comment]
Fair enough! 😅 Quick question… In the interest of clarity, what do you think about renaming this plugin to `pelican-markdown-include`? Would that cause any conflicts with the underlying [Markdown-Include](https://github.com/cmacmackin/markdown-include) dependency?

**Comment by rlaboiss** [comment]
I fully agree with renaming the plugin to `pelican-markdown-include`.

I do not see how this could cause a conflict with the Markdown-Include dependency, but perhaps I misenderstant your question.

**Comment by justinmayer** [comment]
I asked about potential collisions because the renaming would normally cause the plugin package to become `pelican/plugins/markdown_include`, and I wasn't sure if that would cause problems when [importing the Markdown-Include package dependency](https://github.com/rlaboiss/pelican_md_include/blob/2c96e89648cd048d7038bce63c6ec154dab3bde7/pelican/plugins/md_include/md_include.py#L25).

**Comment by rlaboiss** [comment]
Oh, I see. Thanks for the explanation.

I did not realize that changing the name from `md_include` into `pelican-markdown-include` would necessarily imply the change of the directory name from `pelican/plugins/md_include` into `pelican/plugins/markdown_include`.

**Comment by justinmayer** [comment]
Well, technically, it does not necessarily imply that change. I've just been consistently doing things that way, but it doesn't mean that it must _remain_ that way.

That said, it still shows up to end users who manually manage plugins, since they would still need to add `md_include` to their list of `PLUGINS` in that case.

Given that, I wonder if it might be better to retain the existing name, merely for the sake of consistency. Thoughts?

**Comment by rlaboiss** [comment]
There are currently three pelican-markdown-* modules at PyPI, with their corresponding Python include directories :

1. pelican-markdown-image: `pelican/plugins/mdimage`
2. pelican-markdown-unrendered-metadata: `pelican/plugins/markdown_unrendered_metadata`
3. pelican-markdown-it-reader: `pelican/plugins/markdown_it_reader`

We have already an exception to the rule `pelican/plugins/markdown_*`.

I would keep `pelican/plugins/md_include` and just change the name of the plugin to `pelican-markdown-include`.

**Comment by rlaboiss** [comment]
Could we make this move forward? Anything I must do on my side?

**Comment by justinmayer** [comment]
I created the new repository and set up a `migrate` branch with the commits from your personal repo: https://github.com/pelican-plugins/markdown-include/commits/migrate

Next steps to be taken within the `migrate` branch before merging should probably include:

- Renaming the project in `pyproject.toml`, `README.md`, etc.
- Switch to PyPI's trusted publisher system, as recently done in https://github.com/pelican-plugins/yaml-metadata

**Comment by rlaboiss** [comment]
Great, thanks! I will take a look at this as soon as possible.

**Comment by rlaboiss** [comment]
Here we go.

- The project has been renamed as `pelican-markdown-include` (https://github.com/pelican-plugins/markdown-include/commit/1f414737f4d5e016ca1d9a046bd92a7b7a69efec).
- I do not know what you mean exactly by “switch to PyPI's trusted publisher system”, but I changed the file `.github/workflows/main.yaml` to match that of the `yaml-metadata` projec t (https://github.com/pelican-plugins/markdown-include/commit/536d674eb5c4aabf14394daabbb9d28dfd58a28f). My knowledge of GitHub workflows is near to zero, so this commit needs review.

**Comment by rlaboiss** [comment]
Thanks for the corrections and the merge in the `main` branch. It is looking good. Tell me if there is anything else to be done on my side, please. 

I wonder if similar changes as those in https://github.com/pelican-plugins/markdown-include/commit/d4be0e8dc6052d449c90c189b39f27516079ae10, https://github.com/pelican-plugins/markdown-include/commit/c25fa14ff933bcc90919003c74c6bc1c3c6c4c50, and https://github.com/pelican-plugins/markdown-include/commit/a23d4af73edcf37ddf387050a4a6699be862d594, should also be done for the other plugins that I maintain ([graphviz](https://github.com/pelican-plugins/graphviz), [linkclass](https://github.com/pelican-plugins/linkclass), and [avatar](https://github.com/pelican-plugins/avatar)).

**Comment by justinmayer** [comment]
I wouldn't make those changes to your other plugins just yet. The reason is that I am considering a shift in how we handle package builds and dependency management, potentially moving away from Poetry and toward a solution that handles `pyproject.toml` in a standards-compliant manner.

You can see my first experiment with that approach in the https://github.com/pelican-plugins/yaml-metadata repository, which uses a combination of Hatch (build system) and PDM (dependency management).

Once the dust settles and if it seems like a superior method, we can do a whole-scale scripted move to this new tooling.

**Comment by justinmayer** [comment]
Since all the plugins listed here have been migrated, I'm going to close this issue as fully completed. Many thanks for all your contributions, patience, and collaboration! 😁
