### ISSUE TITLE
Static_Comments in reST

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican-plugins#1335]
About Static Comments plugin, its output is formatted in Markdown only.
Is it possible to add the possibility to export in reST also?
Thanks

**Comment by justinmayer** [comment]
Ciao Maurizio. @jesrui contributed the [Static Comments plugin](https://github.com/getpelican/pelican-plugins/tree/master/static_comments) via #172 a long time ago (7 years ago), and it hasn't been touched since. Plugin authors are free to support whatever markup format(s) they choose, and in this case @jesrui implemented support for Markdown and not reST. [As you can see from the code](https://github.com/getpelican/pelican-plugins/blob/master/static_comments/static_comments.py), the logic isn't particularly complicated, so someone with an interest in adding support for reST should be able to do so without too much trouble.

Like most topics involving open source, maintainers barely have enough time to manage the project and almost never have time to implement feature requests. In true open-source form, that progress must almost always come from individual contributors. Maybe try playing with the code and seeing how far you can get? What do you think? :blush:

**Comment by mpaglia0** [comment]
Aha! So you think this is a challenge! :-) OK, I will try
