### ISSUE TITLE
When does extract_toc populate article.toc?

### ISSUE THREAD

**Issue by AWegnerGitHub** [getpelican/pelican-plugins#1370]
This is a question for @talha131 and other extract_toc maintainers.

I am attempting to modify the Flex theme to put the TOC into the side bar. My change to the sidebase.html file prior to the social buttons.

```
{% if article is defined and article.toc %}
      <h1>Article Contents</h1>
      <hr />
      <nav class="toc">
      {{ article.toc }}
      </nav>
    {% endif %}
```

This same change to article.html works as expected. 

---

Through testing, it looks like `article.toc` isn't populated when sidebar is generated. I think this makes sense based on how base.html is laid out but I don't know that for sure.

Base.html trimmed to relevant lines.

```
<body {% if not THEME_COLOR_AUTO_DETECT_BROWSER_PREFERENCE %}class="{{ THEME_COLOR|default('light') }}-theme"{% endif %}>
  
  {% include "partial/sidebar.html" %}

  <main>
  
    {% block content %}
    {% endblock %}
</main>
</body>
```

---

Is there a way that I can get `extract_toc` information "earlier" in the generation process so that I can pull the TOC to the sidebar?

**Comment by talha131** [comment]
@AWegnerGitHub I do not understand the usecase or the issue here.

However, to understand when `extract_toc` is invoked, see this line

https://github.com/getpelican/pelican-plugins/blob/master/extract_toc/extract_toc.py#L66

```py
def register():
    signals.content_object_init.connect(extract_toc)
```

To change the when `extract_toc` is generated, you need to change the signal. More on this is documented [here](https://docs.getpelican.com/en/latest/plugins.html?highlight=signals#list-of-signals).
