### ISSUE TITLE
Asking to move some plugins in the Pelican plugin repo

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican-plugins#1375]
I would like to share my new Pelican plugin.
Do I have to send my commit here or in the new plugin repo?
Thanks!
Maurizio

**Comment by davidlesieur** [comment]
I suggest that you first publish your plugin in a personal GitHub repository, if that's not already the case. Provide detailed documentation, and make sure the code follows the [plugin development guidelines](https://docs.getpelican.com/en/latest/contribute.html#plugin-development). Then update this issue with more detailed information. If you wish to move your plugin into the [pelican-plugins](https://github.com/pelican-plugins) organization, please state it clearly in the issue. A pelican-plugins maintainer might then review it and guide you through the process.

**Comment by mpaglia0** [comment]
Ciao, I desire to submit to your attention the following modules:
Pelican-tweet - a plugin that publish new contents on Twitter (https://github.com/mpaglia0/Pelican-tweet)
Pelican-toot - a plugin that publish new contenss on Mastodon (https://github.com/mpaglia0/Pelican-toot)
Static-comments-plus - an evolution of Static Comments (https://github.com/mpaglia0/Static-Comments-Plus) that let you publish in Markdown or ReST

**Comment by mpaglia0** [comment]
NOTE: I am using Pelican-tweet no more since I abandoned Twitter about one month ago. It is understood this plugin has to be tested in order to see IF it works again since I understood free external apps will work no more with Twitter APIs

**Comment by silverhook** [comment]
I’d love to see the Pelican-toot plugin here :)

**Comment by mpaglia0** [comment]
> I’d love to see the Pelican-toot plugin here :)

It is also my wish

**Comment by justinmayer** [comment]
Ciao Maurizio! Greetings from the Alps in Trentino ⛰️👋

My apologies for the delay in responding to your gracious request. Let’s begin with the Mastodon-related plugin.

My first thought is perhaps we should adjust the name of the plugin. As far as I can tell, Mastodon no longer uses the word “toot” in its product description, marketing pages, et cetera. I believe the Mastodon project has softly deprecated that term and have replaced it with “post”.

Moreover, there is the potential to (eventually) expand the scope of the plugin’s features, given the wide range of functionality provided by the Mastodon API and the [Mastodon.py](https://github.com/halcy/Mastodon.py) Python library. For example, in addition to posting all Pelican articles to a Mastodon account, the plugin could syndicate the last five (non-Pelican-article) Mastodon posts and publish them in a sidebar on the Pelican-powered site, resulting in a two-way flow between the Pelican-powered site and Mastodon (instead of just a one-way flow).

Alternative plugin names could be:

- `pelican-mastodon`
- `pelican-fediverse`
- `pelican-federate`
- `pelican-activitypub`

My inclination is to choose a more generic/expansive name, with the idea that someday the plugin could support alternative/additional API libraries besides the Mastodon-specific [Mastodon.py](https://github.com/halcy/Mastodon.py) library. For example, perhaps something like the [Federation](https://pypi.org/project/federation/) Python package could be used to add support for non-Mastodon ActivityPub servers.

With that in mind, perhaps `pelican-fediverse` might be a good place to start? (With initial support limited to Mastodon and limited to one-way posting of Pelican articles to Mastodon — that is, the plugin’s current behavior).

Any thoughts about these ideas?

**Comment by mpaglia0** [comment]
Ciao Justin and welcome in Italy!!
I understand perfectly and agree with your considerations.
Since I am not a technician and I wrote this plugin only for my limited use on Mastodon, so I used the name Mastodon but - and your vision is correct - I think `pelican-fediverse` should be more appropriate.

**Comment by justinmayer** [comment]
Ciao Maurizio! Thank you for your patience. Let's get the Fediverse plugin transferred so we can begin the process of modernizing it and eventually releasing it to PyPI.

Would you please [follow these transfer instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account)? In step 4, select **Specify an organization or username** and then enter `pelican-plugins` as the organization name. Then go on and complete steps 5 & 6.

Would you please let me know once that has been completed? Then I can take the next steps and ensure you have full permissions there. ✨ 

**Also, we are doing a Pelican sprint this weekend. [Join us and help improve Pelican!](https://github.com/getpelican/pelican/discussions/3212)** ✨

**Comment by mpaglia0** [comment]
Ciao Justin,
trying to close step 4 but when I click on 'I understand, transfer this 
repository' I receive this error:
You don’t have the permission to create public repositories on pelican-plugins

Maurizio

In data sabato 28 ottobre 2023 10:26:13 CEST, Justin Mayer ha scritto:
> pelican-plugins

**Comment by justinmayer** [comment]
Ciao Maurizio. I'm sorry you ran into that error. GitHub makes this process more complicated than it should be, unfortunately. I've invited you to the Pelican Plugins organization as a way to work around that problem; I will adjust the permissions after the transfer is complete.

Would you please try it again and let me know how it goes?

**Comment by mpaglia0** [comment]
Ciao Justin,
accepted the invitation and followed the instructions.
Now I see no more pelican-fediverse among my repos but can see it in 
getpelican area.
I think migration succeeded :-)
Tell me if I have some other steps to take.

Thank you again for this opportunity!

Maurizio



In data domenica 29 ottobre 2023 10:59:32 CET, Justin Mayer ha scritto:
> Ciao Maurizio. I'm sorry you ran into that error. GitHub makes this process
> more complicated than it should be, unfortunately. I've invited you to the
> Pelican Plugins organization as a way to work around that problem; I will
> adjust the permissions after the transfer is complete.
> 
> Would you please try it again and let me know how it goes?

**Comment by justinmayer** [comment]
No more steps left to take. All squared away! New location: https://github.com/pelican-plugins/fediverse

**Comment by mpaglia0** [comment]
Very good!
Now, in order to work on the repo locally I think I have to cancel the local 
repo on my PC and clone the new one from the new location.
Correct?

Thank you,
Maurizio



In data domenica 29 ottobre 2023 18:27:15 CET, Justin Mayer ha scritto:
> No more steps left to take. All squared away! New location:
> https://github.com/pelican-plugins/fediverse

**Comment by justinmayer** [comment]
You can do that, yes, but I believe you can also just change the URL via something like:

    git remote set-url origin https://github.com/pelican-plugins/fediverse.git

(Change the URL to `git@github.com:pelican-plugins/fediverse.git` if you use SSH.)

Various related links that explain in more detail: https://duckduckgo.com/?q=git+change+origin+remote
