### ISSUE TITLE
Intra-site link syntax is not resolved when using the summary plugin

### ISSUE THREAD

**Issue by edelooff** [getpelican/pelican-plugins#314]
When using the summary plugin, if part of the post that is within the summary boundaries contains a link to another article (via {filename} links), the link is not created correctly for the summary.

The following example document demonstrates the problem:

```ReST
Example blogpost
################

:date: 2014-09-23

This article contains a link to `another page`_

.. PELICAN_END_SUMMARY

.. _another page: {filename}hello-world.rst
```

On the created article page, the link will point to `/posts/hello-world`, as expected. However, on pages that display the summary, the link will be to `{filename}hello-world.rst` (this is the exact content of the `href` attribute).

Placing the link target within the summary boundary does not resolve the problem, nor does the use of inline link markup: `` `another page <{filename}hello-world.rst>`_``

This bug happens on Pelican 3.4.0 and the current version of summary that is in the master branch. This bug may be related to #23, though that is purely based on the description of that one, not any form of test.

**Comment by kernc** [comment]
Exactly, the problem is that some plugins fire on `content_object_init` signal and request the objects's `summary` or `content` sometimes before the dependent, linked-to content objects have been processed, so they [don't exist in `self._context['filenames']` when looked up](https://github.com/getpelican/pelican/blob/2fc442fe2d3b0d0dfa2c26db239847bc63bbf16d/pelican/contents.py#L242).

Besides _summary_, I found _share_post_ and _representative_image_ plugins are also affected.

I don't see an easy solution other than creating a new signal "all_generators_finalized" [after all the contexts have been generated in `Pelican.run()`](https://github.com/getpelican/pelican/blob/2fc442fe2d3b0d0dfa2c26db239847bc63bbf16d/pelican/__init__.py#L170), and then amending the plugins to use that signal instead, as @l04m33 recommended.

Would this be accepted as a (two) pull request(s)?

**Comment by justinmayer** [comment]
It sounds like a new "all_generators_finalized" signal would be beneficial. Pull request to that effect would welcome.

**Comment by kernc** [comment]
I'm on it and proceeding wonderfully. But I guess future plugin developers should be warned to avoid `content_object_init` altogether if they do any mangling which includes reading of `_content`.

**Comment by kernc** [comment]
Available for review:
* https://github.com/getpelican/pelican/pull/1616
* https://github.com/getpelican/pelican-plugins/pull/410

Thanks.
