### ISSUE TITLE
Question: extract_toc doesn't work if pandoc isn't available but pandoc_reader is

### ISSUE THREAD

**Issue by Moini** [getpelican/pelican-plugins#582]
I've been trying to use the extract_toc plugin and the pelican_comment_system together, but when I include both into the plugins list, I keep getting a 'File not found' error: 

Traceback: https://gist.github.com/Moini/feb9946a93a1a6282a7e
Installed eggs: https://gist.github.com/Moini/b12dc3e60dfaa9146542
Settings: https://gist.github.com/Moini/ba41742e641760b68c5e

When I take one of them out, it works again. My Pelican version is still 3.5.0 (I'm trying to do one thing at a time ;) ) I've tested with a non-custom theme (simple) and get the same error. 

Update: With pelican 3.6.3, the errors are different, but the result is the same (no website generated):
https://gist.github.com/Moini/7c88a5a6cddf5ed0ff5c

Please let me know if you need more files/info, or if I can try out something that might shed light onto the issue.

**Comment by Scheirle** [comment]
extract_toc and pelican_comment_system together, works fine here. (Pelican 3.5.0, Python 3)
Can you publish your whole setup?

**Comment by Moini** [comment]
Yes, thank you very much! Find it here:
https://github.com/Moini/pelican-website
(will remove it again when we're done) 

Using python 2.7.6 here in the virtualenv.
infos.txt contains additional infos you might need, in addition to .gitignore. 
I hope it's complete - it's a first time for me (I don't use version control for my other repos...). If not, please ask. Thanks again!

**Comment by Scheirle** [comment]
Your site also works fine here (Pelican 3.5.0, Python 3 / 2.7.6)

Did you try to remove the folders `output`, `cache` and `__pycache__` and/or run pelican with the `--ignore-cache` flag?

My Pelican version contains one additional commit: <https://github.com/Scheirle/pelican/commit/39cb3a228de210e2072cc1bcebcc4a929f1c5b4f> (Reason:  https://github.com/getpelican/pelican/pull/1306)
But even with out this commit, your site still works here.

**Comment by Moini** [comment]
Thank you very much for trying it out! 
So the problem must be on my end... :/

I created the directory from scratch for testing (now a second time), with only in it what is inside the git repo, re-installing virtualenv and plugins, and re-establishing output (not cache, pelican 3.6.3 doesn't seem to create one anymore automatically). Guess I'm doing something wrong... :(

I've 'recorded' what I did: 
https://gist.github.com/Moini/fea1bcb9fd419c5c0fda - maybe you can see what I'm doing differently from you?

**Comment by RocMax** [comment]
Hi,I have the same problem.
Using Pelican 3.6.3, Python 2.7.10
I didn't use pelican_comment_system plugin ,my plugin list: 'sitemap','render_math','extract_toc','tipue_search'.
I'm still working on it.

**Comment by Scheirle** [comment]
> I've 'recorded' what I did:
https://gist.github.com/Moini/fea1bcb9fd419c5c0fda - maybe you can see what I'm doing differently from you?

I followed the first 11 lines (Had to adjust the `PHOTO_LIBRARY` Path in `pelicanconf.py`) and it works for me.

My System: Ubuntu 14.04

**Comment by RocMax** [comment]
Hey,I made some progress for this .
By checking the traceback I found that error occurs at
```
/pelican-plugins/pandoc_reader/pandoc_reader.py", line 34, in read stdout = subprocess.PIPE)
```
but actually pandoc_reader was not in my plugin list.
In extract_toc.py line 14
```
try:
    from pandoc_reader import PandocReader
except ImportError:
    PandocReader = False
```
looks like extract_toc.py automatically imports pandoc_reader and the error occurs at pandoc_reader.py
```
proc = subprocess.Popen(pandoc_cmd,
                                stdin = subprocess.PIPE,
                                stdout = subprocess.PIPE)
```
`stdout = subprocess.PIPE`may have some PATH problem.  I'm trying to solve it.

**Comment by avaris** [comment]
You probably don't have `pandoc` installed (or in `PATH`). `pandoc_reader` replaces default markdown reader but relies on `pandoc`. If you're not using it, you're better off with removing `pandoc_reader` from your plugins folder.

**Comment by Moini** [comment]
So would it make sense to try to detect if pandoc is available before trying to import pandoc_reader? (not sure if I understood everything correctly - hope this isn't a silly question)

**Comment by avaris** [comment]
Sort of. There are a couple of ways to go around this. `pandoc_reader` could be a little more intelligent and *not* replace markdown reader if `pandoc` isn't available. Or, `extract_toc` could do it better.

TBH, finding a way to do it without importing `pandoc_reader` in `extract_toc` would be better. Because reader plugins are a bit special. Even importing them at the proper spot is enough to *activate* them.

But for the time being, if you want a quick-fix, just get rid of `pandoc_reader` from your plugins :).

**Comment by RocMax** [comment]
I tried to delete the code that checking whether pandoc_reader is exist and just return False  in extract_toc.py 
```python
#try:
#    from pandoc_reader import PandocReader
#except ImportError:
PandocReader = False
```
the error never occur again.This maybe a solution.
But then I noticed that `toc` turned into None , and the "Contents" sidebar disappeared(using elegant theme) ,so I still want to make pandoc_reader working properly.
BTW:I found a few issues about relationship between `stdout = subprocess.PIPE` and `raise child_exception` in [here](http://stackoverflow.com/questions/24161476/subprocess-popen-simple-code-does-not-allow-me-to-perform-a-cd-change-directory) and [here](http://stackoverflow.com/questions/14810160/no-such-file-or-directory-with-subprocess-popen-not-caused-by-string-command) . I'm not quite versed in python , according to their discussions I guess that the error is because `pandoc_cmd` runs in wrong path. I'm still learning about it.
