### ISSUE TITLE
[Photos] Current documentation does not work

### ISSUE THREAD

**Issue by shaaati** [getpelican/pelican-plugins#723]
I just set up the Photos Plugin with my blog. When trying to adjust the template as stated in the README file pelican produed an error due to the fact that
article.photo_gallery does not, as mentioned, hold 5-tuples for each photo inside the gallery associated to the article but a tuple of the gallery name in its first element and a list with the 5-tuples describing the pictures in its second element.

I changed the code added to the article.html template file as follows:
```
{% if article.photo_gallery %}
  <div class="gallery">
    {% for gallery in article.photo_gallery %}
      {% for name, photo, thumb, exif, caption in gallery[1] %}
        <a href="{{ SITEURL }}/{{ photo }}" title="{{ name }}" exif="{{ exif }}" caption="{{ caption }}"><img src="{{ SITEURL }}/{{ thumb }}"></a>
      {% endfor %}
    {% endfor %}
  </div>
{% endif %}
```
As I am not yet very familiar with Pelican, Plugins, and theming, this solution works but does not feel to be the correct one. I am sure that there is a more correct way of doing it.

Anyway, the documentation should probably be corrected to reflect that problem.

**Comment by bnice5000** [comment]
I am using a different method that I think is what the author of the plugin update is trying to do with the revision. You can unpack both the name of the gallery and the gallery info without having to use a set index.

However, it is kind of silly because the title of gallery is going to be a folder name and therefore most likely useless. If the update author wanted to make this more useful he might want to include a way to include an arbitrary title.

```
{% for title, gallery in article.photo_gallery %}
  {% for name, photo, thumb, exif, caption in gallery %}
      <img src="{{ SITEURL }}/{{ photo }}" exif="{{ exif }}" alt="{{ caption }}">
  {% endfor %}
{% endfor %}
```
