### ISSUE TITLE
Shouldn't i18n_subsites use hreflang?

### ISSUE THREAD

**Issue by born2webdesign** [getpelican/pelican-plugins#726]
Hi,  shouldn't the i18n_subsites plugin use hreflang to point to other language versions?
https://sites.google.com/site/webmasterhelpforum/en/faq-internationalisation

**Comment by avaris** [comment]
"This" = What?

**Comment by born2webdesign** [comment]
Right, there is more than one plugin :D
"This" = i18n_subsites – sorry.

**Comment by avaris** [comment]
Can you update the title so that people interested can find it easily?

**Comment by born2webdesign** [comment]
If you want some "reference" implementations, Joomla's native multi-lingual system uses them, as does e.g. the polylang plugin for WordPress (and many others, I'm sure).

**Comment by smartass101** [comment]
Interesting idea. However, the `i18n_subsites` plugin only modifies the core Pelican translations behavior and logic, so this issue should be moved to Pelican core where the translations are actually handled.

**Comment by justinmayer** [comment]
@born2webdesign: Is this something you would like to work on implementing?

**Comment by jorgesumle** [comment]
This is something I would like to add to the themes included with Pelican. It should be something like this.

```
{% macro entry_hreflang(entry) %}
{% if entry.translations %}
  {% for translation in entry.translations %}
    <link rel="alternate" hreflang="{{ translation.lang }}" href="{{ SITEURL }}/{{ translation.url }}">
  {% endfor %}
{% endif %}
{% endmacro %}
```

Which then is added to `article.html`...

```
{% import 'translations.html' as translations with context %}
{% if translations.entry_hreflang(article) %}
  {{ translations.entry_hreflang(article) }}
{% endif %}
```

and `page.html`...

```
{% import 'translations.html' as translations with context %}
{% if translations.entry_hreflang(page) %}
  {{ translations.entry_hreflang(page) }}
{% endif %}
```

Also, we must add the `hreflang` attribute to `<a>` elements. I can implement all this after https://github.com/getpelican/pelican/pull/2370 gets merged or I can add more commits to it if maintainers prefer that.

The previously mentioned improvements don't require any plugin. If you want to add the `hreflang` attributes to the `index.html` page of a site using `i18n_subsites`, you should include the following code in that file inside the `<head>` element...

```
  {% if lang_siteurls and articles_page.number == 1 %}
    {% for lang, url in lang_siteurls.items() %}
      <link rel="alternate" hreflang="{{ lang }}" href="{{ url }}/">
    {% endfor %}
  {% endif %}
```

Note that it only includes it on the first page. That's because we could have 20 pages in one language and 4 in another, that way we don't include broken links by mistake.

In my opinion, i18n_subsites gives you the variables needed to implement this functionality in your themes, and a plugin shouldn't modify the templates. Therefore, I think this issue should be closed, maybe adding the relevant documentation to i18n_subsites if you think that's necessary.

**Comment by justinmayer** [comment]
Ostensibly addressed by https://github.com/getpelican/pelican/pull/2374.
