### ISSUE TITLE
pelican_comment_system: empty feed unnecessary upload on rsync --checksum

### ISSUE THREAD

**Issue by notionsandnotes** [getpelican/pelican-plugins#780]
I use `rsync` with the `--checksum` option to upload only newly modified files.

For every article with no comments, the comment feed file is being generated and uploaded again at each run of `make rsync_upload`. The other files, if unmodified, even if freshly generated, do not pass the checksum criterion and thus do not get unnecessarily uploaded.

**Comment by Scheirle** [comment]
This is not that easy to fix.

The problem is that the `updated` element of the feed gets set to the date of the latest feed item / comment.
Since there are no feed items it get set to the current time [1] and therefore changes on every run.

A workaround would be to add a dummy feed item (ala 'There are no comments yet') but this has other disadvantages.
Feed readers normally do not delete feed items and therefore this dummy item would always be visible.

A other workaround would be to monkey patch the `latest_post_date` function, but this is obviously bad design and likely brakes in the future.

[1] https://github.com/getpelican/feedgenerator/blob/6b6572cfd3e7f40993204af5aa70aab443a5b63c/feedgenerator/django/utils/feedgenerator.py#L196

**Comment by notionsandnotes** [comment]
Why not set it to the `Modified:` date of the article and if absent, to simply the `Date:` of the article?

**Comment by Scheirle** [comment]
Because neither pelican nor feedgenerator offer an api to set the element directly.

**Comment by notionsandnotes** [comment]
I see. Thanks for explaining.

**Comment by Scheirle** [comment]
I pushed a patch to <https://github.com/Scheirle/pelican-plugins/tree/pcs_fix780> 
Commit: https://github.com/Scheirle/pelican-plugins/commit/b1b5c1ee4faefff3944a66359bbca86de483911c

I didn't create a PR as the patch currently contains two flaws, I'm not pleased with.
