### ISSUE TITLE
Enable python-render-math plugin for the markdown handling in render_math?

### ISSUE THREAD

**Issue by danmackinlay** [getpelican/pelican-plugins#827]
We know there is a [python markdown math extension](https://github.com/mitya57/python-markdown-math), maintained by @mitya57.

 In #693 @justinmayer  touched upon the need for test coverage, and in #787 @jar1karp noticed the render_math custom parsing conflicts with the summary plugin. I wonder if we can improve both these issues by using a third-party dependency? It seems to have test coverage be well-behaved in the trivial case. Has anyone tried using it? Perhaps @barrysteyn had a reason for rejecting it previously? Or perhaps it simply didn't exist when he started render_math?

Does anyone have compelling reasons we should NOT use it to benefit from the work there?

**Comment by barrysteyn** [comment]
Hi

This Python extension is relative recent, and it was made after (or around about the same time) as I made my extension. Both my extension and the extension you point do actually do very similar things. However my extension has been specifically adapted to Pelican (for example, I handle summaries which is a Pelican concept).

Before you decide to move, make sure that it can be adapted (for example, look at configs that render_math can handle).

**Comment by howthebodyworks** [comment]
Of course that's reasonable @barrysteyn; I'm mostly interested because saving test-writing effort will be a win;
Obviously we don't want to lose functionality except in extremis.
That said, have you noticed the [difficulties with summaries for render_math](https://github.com/getpelican/pelican-plugins/pull/787#issuecomment-268959471) for current pelican? I wonder if _any_ amount of code will handle summaries at the moment, given the summary memoization problem? That part is not clear to me; will have to wait until someone has time to try.

**Comment by danmackinlay** [comment]
OK, we have many other more pressing issues.
