### ISSUE TITLE
Plantuml-plugin-not-rendering-diagrams

### ISSUE THREAD

**Issue by tooh** [getpelican/pelican-plugins#833]
http://stackoverflow.com/questions/41406183/pelican-plantuml-plugin-not-rendering-diagrams

Tried to solve this by issuing question on SO. No results sofar.

**Comment by julianrendell** [comment]
I just hit similar problems.

In my error log I noticed `[plantuml] Markdown support not available`. Commenting out the exception handling (to get the stack trace) lead me to the following quick hack:

```
--- a/plantuml/plantuml_rst.py
+++ b/plantuml/plantuml_rst.py
@@ -68,21 +68,12 @@ def pelican_init(pelicanobj):
     """ Prepare configurations for the MD plugin """
     try:
         import markdown
-        from plantuml_md import PlantUMLMarkdownExtension
+        from .plantuml_md import PlantUMLMarkdownExtension
     except:
         # Markdown not available
         logger.debug("[plantuml] Markdown support not available")
         return

-    # Register the Markdown plugin
-    config = { 'siteurl': pelicanobj.settings['SITEURL'] }
-
-    try:
-        pelicanobj.settings['MD_EXTENSIONS'].append(PlantUMLMarkdownExtension(config))
-    except:
-        logger.error("[plantuml] Unable to configure plantuml markdown extension")
-
-
 def register():
     """Plugin registration."""
     signals.initialized.connect(pelican_init)
```

The first part fixed a problem with paths/finding `plantuml_md.py`.

The second was needed because there have been changes to how markdown extensions are handled in Pelican.

There's a wrinkle with this plugin- it not only has to register with Pelican, but also with the markdown processor. It'd be nice if adding it as a Pelican plugin would still do the later. But in the time I had, I couldn't figure out the 'right way' for the plugin to register itself as a markdown extension.

So I also modified `pelicanconf.py`:

```
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight',
                                           'linenums': False,
                                           'use_pygments': False},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.toc' : {},
        'plantuml.plantuml_md': {},
    },
    'output_format': 'html5',
}
```

From what I read/observed, Pelican now auto-adds markdown extensions by using the keys in the `extension_configs` dictionary. Adding the `plantuml.plantuml_md` was needed to hook it all together.

Now something like the following in a markdown file works:

```
::uml::
start
:step 1;
:step 2;
:step 3;
stop
::end-uml::
```

**Comment by tooh** [comment]
@julianrendell  Thanks for your reply. I tried your hack, but could not make it work. I applied your code alterations in plantuml_rst.py and the addition to the pelicanconf.py.
Can you share your complete version on these files form clarification ?

**Comment by tooh** [comment]
@julianrendell  Hm, I don't know what I exactly did, but now it is working.
Please claim your credits by describing your fix on SO
http://stackoverflow.com/questions/41406183/pelican-plantuml-plugin-not-rendering-diagrams
