### ISSUE TITLE
{attach} incompatible with representative_image

### ISSUE THREAD

**Issue by mwcz** [getpelican/pelican-plugins#854]
I'm using `{attach}` to allow keeping static assets alongside my posts.  [These instrcutions](http://docs.getpelican.com/en/latest/content.html#mixed-content-in-the-same-directory) work great.  However, the representative_image plugin doesn't resolve the `{attach}`.

Post:

    Title: Test
    Date: 2012-01-01

    ![test]({attach}image.png)

Output of `{{ article.featured_image }}`:

`<img src="{attach}ss.png" />`

**Comment by avaris** [comment]
I don't think it's about the `{attach}`. The plugin [uses `._content`](https://github.com/getpelican/pelican-plugins/blob/master/representative_image/representative_image.py#L28) which is unprocessed, therefore contains unresolved links. Either it should resolve the links itself, or it should use `.content`. 

Though, this plugin will have issues. I seriously doubt that this plugin will produce meaningful output with `RELATIVE_URLS` setting. And, given that it'd use `.content`, no other plugin after this can modify `._content` because it'll be memoized and changes will not be visible. I'm afraid, these aren't easy to fix.

**Comment by mwcz** [comment]
Understood, thank you for the explanation.  I'll go with the only slight inconvenience of `Image: /2017/01/01/my-post-slug/thumb.jpg` in the post metadata.
