### ISSUE TITLE
rmd_reader knits again all the rmd documents when running make

### ISSUE THREAD

**Issue by chrplr** [getpelican/pelican-plugins#897]
Every time I run 'make html', rmd_reader knits all the Rmd documents again, which can last for long time.

**Comment by justinmayer** [comment]
@chrplr: Were you able to find a solution to your problem here?

**Comment by trevorld** [comment]
It is easy to solve this problem outside ``pelican`` by using a build tool like ``make``, ``rake``, etc instead of using the ``rmd_reader``.

1. Have a "rule" that generates ``md`` files from ``Rmd`` files using ``Rscript`` and ``knitr::knit()``
2. Make any ``pelican`` "tasks" depend on all those ``md`` files

Then when you run one of your pelican tasks it should only knit new (or edited) Rmd documents and not the old ones.

Here is one of my [R based website's Rakefile](https://github.com/piecepackr/piecepackr_site/blob/master/Rakefile) which does this for the analogous case of knitting ``.Rrst`` files to ``.rst`` files before building the site with ``pelican``.

**Comment by justinmayer** [comment]
Many thanks for the suggestion, Trevor. Given your suggested solution, as well as the fact that this issue has been around for a while, I think we can consider it resolved. 💫
