### ISSUE TITLE
[subcategory] access to subcategories in templates

### ISSUE THREAD

**Issue by oulenz** [getpelican/pelican-plugins#989]
@alistairmagee

I have two pull requests that fix some things that I needed to use the subcategory plugin in my project. They change the semantics of subcategories to some extent, so I am not sure whether they fit the spirit of this plugin. The two pull request may be seen as alternatives, the second being more radical.

https://github.com/getpelican/pelican-plugins/pull/990
https://github.com/getpelican/pelican-plugins/pull/991

- The first pull requests adds `subcategories` to the context, so it can be used in templates
- It also adds categories as subcategories. Ie, categories appear twice, as categories and as subcategories. The main reason is that `subcategories` is pretty useless if it doesn't contain the top-level categories, and I didn't see what purpose the distinction between top-level categories and proper subcategories serves.
- I am not sure I see the use-case for having both categories and subcategories at all, so the second pull request simply redefines subcategories as categories.

---

There are a number of ideas that I didn't include in these pull requests but that I'll list here for context:

- Adding a setting to only include articles in their most specific subcategory
- Adding a list of children to each category to allow more fine-grained access when building menus
- Redefining the index as the unique root category (not sure whether this isn't more trouble than it's worth)

**Comment by alistairmagee** [comment]
Hi Oulenz

It's been a long time since I had a look at any of this stuff.

I believe I made Categories and Subcategories separate so that existing templates would not break. ie. All templates implement categories as they normally are. On my site I only had to change the existing navigation template to

```
<nav>In:
        <ol class="category-list">
            <li>
                <a href="{{ SITEURL }}/{{ article.category.url }}">{{ article.category }}</a>
            </li>
            {% include "subcategorylist.html" %}
        </ol>
    {% include "taglist.html" %}
    </nav>
```
And subcategorylist.html is 

---
{% if article.subcategories %}{% for subcategory in article.subcategories %}
<li>
    <a href="{{ SITEURL }}/{{ subcategory.url }}">{{ subcategory.shortname }}</a>
</li>    
{% endfor %}{% endif %}
---

I thought making it easy to update existing templates to accommodate Subcategories without breaking templates for websites without them. 

I don't know what other plugins and Templates rely on the behaviour of Categories as it currently stands so I don't think its a good idea to change the way they are defined completely. So I don't think it's a good idea to merge #991.

Can you explain exactly what you are accomplishing with #990 that you couldn't do before? Reading through it seems like it's mostly just changing the name `fullurl` to `slug` which I can see making sense as the old slug value is still accessible using the `shortname` value. If that is somehow more consistent with the way Pelican does things elsewhere happy to change it, but I'm not sure why that is causing you any problems the way it currently is. It certainly reads nicer, I just don't want to have missed something. 


In regards to your extra ideas:

###Adding a setting to only include articles in their most specific subcategory.

What is the use case of this? I don't understand as I originally wrote this plugin for the exact opposite reason. I had a website that had a blog and multiple webcomics. Categories and Sub-Categories were
`Blog`, `Comics/Comic1` and `Comics/Comic2`, I wanted to let people just read, for example, Comic2. So needed a navigation that would allow that. Alternatively they could navigate to any Comic polst but not the Blog. Or alternatively they could read everything on the site. 

That's why I also wrote the neighbours plugin so i could easily set up intra category/sub-category navigation links.

###Adding a list of Children to each category for menues

Sounds cool

###Redefining the index as the unique root category
Not sure I completely understand this. Is this so each page has a Category as well?

**Comment by oulenz** [comment]
Hi Alistair, thank you for taking the time to reply even though you may no longer be working on this!

The main problem this solves is that it adds the variable `subcategories` to the context, so it becomes possible to display all subcategories in the menu. (Not just the subcategories of an article, _all_ subcategories.) In addition, it adds categories as top-level subcategories, because otherwise there's little point. Is there a reason why you didn't let categories also be top-level subcategories?

I admit that I didn't think of people using this plugin with existing templates, although it seems to me they  wouldn't gain anything from it?

I think it may be worth exploring how exactly #991 would break existing behaviour, and whether any issues cannot be fixed. Do you see any breaking changes?

In this respect, I would like to point out that the current version of this plugins actually changes vanilla behaviour if ` USE_FOLDER_AS_CATEGORY == True`.

**Comment by alistairmagee** [comment]
Okay I understand now. That is very useful.

Re: templates

yeah you get no benefit if you don't modify your templates. I was more
thinking that every existing theme currently handles categories in a
certain way, adding subcategories to that seems easier than modifying the
way categories is handled. Maybe not.

It does seem easier if someone wants to go the other way. If a theme is
written that has subcategory support but someone wants to use it without,
it should still handle normal categories correctly. But that is a very
specific circumstance I guess.

Re: use folder as category

This has been a problem since I wrote the plugin, because I didn't even
think about it. If one of your pull requests fixes that then that should be
done. It's something I meant to fix, but because I didn't need it it always
fell off the to do list.

Just a last thing, I'm happy to change things if they add more
functionality, but I don't know how many people use this plugin. I don't
want to break things for people. So it seems a bad idea to change existing
behaviour. Adding subcategories to the context just adds a feature do
that's fine. But changing the variable names and the behaviour of
categories vs subcategories requires changes to settings files and
templates for people already using it. There should be a good reason for it.

**Comment by oulenz** [comment]
I agree that backwards compatibility should be a concern, and I could live with my proposals ending up in a separate plugin if the changes are too disruptive. That said, my impression is that the main pelican program doesn't shy away from breaking changes, and I wonder whether plugins should be different in this regard (they aren't versioned so that might give users insufficient control).

#990 is currently not backwards compatible since it adds the category to the subcategories of an article. I guess this could be reversed while still adding categories to the global subcategories variable. Apart from that, #990 shouldn't break things for people.

**Comment by voidplayer** [comment]
Is it possible to make ```category.categories``` as a list of categories? Backwards compatible and adds new functionality

To me this seems useful enough to be baked on pelican instead of a plugin, but not sure if it would be accepted

**Comment by oulenz** [comment]
Resolved by https://github.com/getpelican/pelican-plugins/pull/1082 (new `more_categories` plugin that  also handles multiple categories)
